import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Joe',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'john@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: 'Yellow T-shirt',
      image: '/images/t1.jpg',
      price: 30,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality T-shirt',
    },
    {
      name: 'White T-shirt',
      image: '/images/t2.jpg',
      price: 20,
      countInStock: 20,
      brand: 'Hanes',
      rating: 4,
      numReviews: 15,
      description: '100% Cotton T-shirt',
    },
    {
      name: 'Black T-shirt',
      image: '/images/t3.jpg',
      price: 20,
      countInStock: 13,
      brand: 'Hanes',
      rating: 4.5,
      numReviews: 10,
      description: '100% Cotton T-shirt',
    },
    {
      name: 'Women Casual Wear',
      image: '/images/t4.png',
      price: 50,
      countInStock: 0,
      brand: 'Abercrombie',
      rating: 4.5,
      numReviews: 18,
      description: 'High quality Shirt',
    },
    {
      name: 'Men Casual Wear',
      image: '/images/t5.jpg',
      price: 45,
      countInStock: 13,
      brand: 'Urban Outfitter',
      rating: 4.5,
      numReviews: 12,
      description: 'High quality Shirt',
    },
    {
      name: 'Women Dress',
      image: '/images/t6.jpg',
      price: 65,
      countInStock: 15,
      brand: 'Abercrombie',
      rating: 5,
      numReviews: 10,
      description: 'High quality Dresswear',
    },
    {
      name: 'Women Graphic Tee',
      image: '/images/t7.jpg',
      price: 30,
      countInStock: 0,
      brand: 'Nike',
      rating: 5,
      numReviews: 8,
      description: 'High quality Graphic Tee',
    },
    {
      name: 'Men Graphic Tee',
      image: '/images/t8.jpg',
      price: 30,
      countInStock: 0,
      brand: 'Nike',
      rating: 5,
      numReviews: 11,
      description: 'High quality Graphic Tee',
    },
  ],
};

export default data;
